import Foundation
import Testing
@testable import PoliVerse

/// The little HTML reading the Manifesti degli Studi needs.
///
/// That service is a Struts application from another era: HTML, no API behind
/// it, and markup generated by a template engine — which is the only reason
/// reading it with regular expressions is a defensible trade. These tests
/// state the shapes that trade covers, so the day a page needs real nesting is
/// a day a test fails rather than a day a screen quietly empties.
@Suite("Lettura dell’HTML dei Manifesti")
struct HTMLScraperTests {
    /// A teaching page's card, in the markup the service produces.
    private let card = """
    <table class="BoxInfoCard">
      <tr><td class="TitleInfoCard">Informazioni generali</td></tr>
      <tr><td class="ElementInfoCard1">Codice</td><td class="ElementInfoCard2">052496</td></tr>
      <tr><td class="ElementInfoCard1">Docente</td>
          <td class="ElementInfoCard2"><a href="…">Rossi Matteo&nbsp;Giovanni</a></td></tr>
      <tr><td class="ElementInfoCard1">Crediti</td><td class="ElementInfoCard2">  10  </td></tr>
      <tr><td class="TitleInfoCard">Programma</td></tr>
      <tr><td class="ElementInfoCard1">Argomenti</td><td class="ElementInfoCard2">Grafi</td></tr>
    </table>
    """

    // MARK: Le schede

    @Test("Il valore accanto a un’etichetta si legge, ripulito")
    func cardValue() {
        #expect(HTMLScraper.cardValue("Codice", in: card) == "052496")
        #expect(HTMLScraper.cardValue("Crediti", in: card) == "10", "Gli spazi attorno al valore restano fuori")
    }

    /// The value often carries the link that identifies the thing it names;
    /// what the caller wants is the text, entities and all.
    @Test("Un valore con dentro un collegamento torna come testo")
    func cardValueWithMarkup() {
        #expect(HTMLScraper.cardValue("Docente", in: card) == "Rossi Matteo Giovanni")
    }

    @Test("Un’etichetta che non c’è non torna niente")
    func missingLabel() {
        #expect(HTMLScraper.cardValue("Propedeuticità", in: card) == nil)
    }

    /// An empty cell is "not stated", not an empty answer to show.
    @Test("Un valore vuoto vale come assente")
    func emptyValue() {
        let html = #"<td class="ElementInfoCard1">Docente</td><td class="ElementInfoCard2">  </td>"#
        #expect(HTMLScraper.cardValue("Docente", in: html) == nil)
    }

    @Test("Le coppie di una scheda tornano tutte, nell’ordine della pagina")
    func cardPairs() {
        let pairs = HTMLScraper.cardPairs(in: card)
        #expect(pairs.map(\.label) == ["Codice", "Docente", "Crediti", "Argomenti"])
        #expect(pairs.first?.value == "052496")
    }

    // MARK: Le sezioni

    /// Sections are announced by a title and run until the next one; there is
    /// no container element to scope them with.
    @Test("Una sezione va dal suo titolo al successivo")
    func section() throws {
        let general = try #require(HTMLScraper.section("Informazioni generali", in: card))
        #expect(general.contains("052496"))
        #expect(!general.contains("Grafi"), "La sezione ha sconfinato in quella dopo")

        let programme = try #require(HTMLScraper.section("Programma", in: card))
        #expect(programme.contains("Grafi"))
        #expect(!programme.contains("052496"))
    }

    @Test("L’ultima sezione arriva fino in fondo alla pagina")
    func lastSection() throws {
        let programme = try #require(HTMLScraper.section("Programma", in: card))
        #expect(programme.contains("</table>"))
    }

    @Test("Una sezione che non c’è non torna niente")
    func missingSection() {
        #expect(HTMLScraper.section("Valutazione", in: card) == nil)
    }

    // MARK: Le tabelle

    @Test("Le righe tornano con le celle grezze, che portano i collegamenti")
    func rows() throws {
        let html = """
        <table>
          <tr><th>Codice</th><th>Insegnamento</th></tr>
          <tr><td>052496</td><td><a href="/teaching?id=7">Algoritmi</a></td></tr>
          <tr><td>059156</td><td><a href="/teaching?id=9">Analisi</a></td></tr>
        </table>
        """
        let rows = HTMLScraper.rows(in: html)

        #expect(rows.count == 3, "L’intestazione è una riga come le altre")
        #expect(rows[0] == ["Codice", "Insegnamento"])
        #expect(rows[1][0] == "052496")
        #expect(rows[1][1].contains("href=\"/teaching?id=7\""), "La cella ha perso il collegamento che la identifica")
    }

    @Test("Una tabella senza righe non inventa righe")
    func noRows() {
        #expect(HTMLScraper.rows(in: "<table></table>").isEmpty)
    }

    // MARK: I collegamenti

    @Test("Il primo href di un frammento torna deescapizzato")
    func href() {
        let html = #"<a href="/manifesto?evn_dettaglio=1&amp;c_classe=755166">Vedi</a>"#
        #expect(HTMLScraper.href(in: html) == "/manifesto?evn_dettaglio=1&c_classe=755166")
    }

    @Test("Un frammento senza collegamenti non ne inventa uno")
    func noHref() {
        #expect(HTMLScraper.href(in: "<td>Algoritmi</td>") == nil)
    }

    /// The same service spells its events `EVN_DETTAGLIO_RIGA_MANIFESTO` in
    /// one link and `evn_default` in the next, and its parameter names drift
    /// the same way — so the name is matched without regard to case.
    @Test("Un parametro si legge comunque sia scritto")
    func queryValue() {
        let url = "/manifesto?EVN_DETTAGLIO=1&c_classe=755166&lang=IT"
        #expect(HTMLScraper.queryValue("c_classe", in: url) == "755166")
        #expect(HTMLScraper.queryValue("C_CLASSE", in: url) == "755166")
        #expect(HTMLScraper.queryValue("evn_dettaglio", in: url) == "1")
    }

    @Test("Il valore di un parametro torna decodificato")
    func queryValueEncoded() {
        #expect(HTMLScraper.queryValue("nome", in: "/x?nome=Analisi%20Matematica") == "Analisi Matematica")
    }

    /// A parameter whose name merely ends the same way is not the parameter
    /// asked for: only `?` or `&` start one.
    @Test("Un parametro con un nome che finisce uguale non conta")
    func queryValueNotASuffix() {
        #expect(HTMLScraper.queryValue("classe", in: "/x?c_classe=755166") == nil)
    }

    @Test("Un parametro che non c’è non torna niente")
    func missingQueryValue() {
        #expect(HTMLScraper.queryValue("k_doc", in: "/manifesto?c_classe=755166") == nil)
    }

    // MARK: Il testo

    @Test("Il testo perde i tag, scioglie le entità e stringe gli spazi")
    func text() {
        #expect(HTMLScraper.text("<p>Analisi &amp;   Geometria</p>") == "Analisi & Geometria")
    }
}
