import Foundation

/// The small amount of HTML parsing the Manifesti degli Studi needs.
///
/// That service is a Struts application from another era: it answers HTML, not
/// JSON, and there is no API behind it. Rather than pull in a DOM parser for
/// four shapes, this reads the three structures the pages actually use —
/// label/value cards, tables, and links — with regular expressions.
///
/// That is a deliberate trade with a stated limit: this is **not** an HTML
/// parser and must not be asked to become one. It works because the markup is
/// machine-generated by a template engine and therefore regular. The moment a
/// page needs real nesting, the answer is a parser, not another expression.
nonisolated enum HTMLScraper {
    /// Tags stripped, entities decoded, whitespace collapsed.
    static func text(_ html: String) -> String {
        HTMLText.plain(html)
    }

    /// The value beside a label in a `BoxInfoCard` table.
    ///
    /// The markup is `<td class="ElementInfoCard1">Label</td>` followed by
    /// `<td class="ElementInfoCard2">Value</td>`, which is how every field on
    /// the teaching page is expressed.
    static func cardValue(_ label: String, in html: String) -> String? {
        let pattern = """
        ElementInfoCard1[^>]*>\\s*\(NSRegularExpression.escapedPattern(for: label))\\s*\
        </td>\\s*<td[^>]*ElementInfoCard2[^>]*>(.*?)</td>
        """
        guard let match = firstMatch(pattern, in: html, group: 1) else { return nil }
        return text(match).nonEmpty
    }

    /// Every label/value pair of a card, in order.
    static func cardPairs(in html: String) -> [(label: String, value: String)] {
        let pattern = "ElementInfoCard1[^>]*>(.*?)</td>\\s*<td[^>]*ElementInfoCard2[^>]*>(.*?)</td>"
        return matches(pattern, in: html).compactMap { groups in
            guard groups.count >= 2 else { return nil }
            let label = text(groups[0]), value = text(groups[1])
            guard !label.isEmpty else { return nil }
            return (label, value)
        }
    }

    /// Rows of a table, each as its cells' raw HTML.
    ///
    /// Raw rather than text, because a cell often carries the link that
    /// identifies the thing it names — a teacher's `k_doc`, a module's code.
    static func rows(in html: String) -> [[String]] {
        matches("<tr[^>]*>(.*?)</tr>", in: html).compactMap { groups in
            guard let row = groups.first else { return nil }
            let cells = matches("<t[dh][^>]*>(.*?)</t[dh]>", in: row).compactMap(\.first)
            return cells.isEmpty ? nil : cells
        }
    }

    /// The first `href` in a fragment, unescaped.
    static func href(in html: String) -> String? {
        firstMatch("href=\"([^\"]+)\"", in: html, group: 1)
            .map { $0.replacingOccurrences(of: "&amp;", with: "&") }
    }

    /// A query parameter's value from a URL string.
    ///
    /// Case-insensitive on the name: the same service spells its events
    /// `EVN_DETTAGLIO_RIGA_MANIFESTO` in one link and `evn_default` in the
    /// next, and its parameter names drift the same way.
    static func queryValue(_ name: String, in url: String) -> String? {
        let pattern = "[?&]\(NSRegularExpression.escapedPattern(for: name))=([^&\"#]*)"
        return firstMatch(pattern, in: url, group: 1, caseInsensitive: true)?
            .removingPercentEncoding
    }

    /// Everything between a section title and the next one.
    ///
    /// Sections are announced by `<td class="TitleInfoCard">Name</td>`, and
    /// run until the following title — there is no container element to scope
    /// them with.
    static func section(_ title: String, in html: String) -> String? {
        let escaped = NSRegularExpression.escapedPattern(for: title)
        guard let start = range(of: "TitleInfoCard[^>]*>\\s*\(escaped)", in: html) else {
            return nil
        }
        let rest = String(html[start.upperBound...])
        guard let next = range(of: "TitleInfoCard", in: rest) else { return rest }
        return String(rest[..<next.lowerBound])
    }

    // MARK: - Regex plumbing

    private static func range(
        of pattern: String, in html: String
    ) -> Range<String.Index>? {
        html.range(of: pattern, options: [.regularExpression, .caseInsensitive])
    }

    static func firstMatch(
        _ pattern: String, in html: String, group: Int, caseInsensitive: Bool = true
    ) -> String? {
        var options: NSRegularExpression.Options = [.dotMatchesLineSeparators]
        if caseInsensitive { options.insert(.caseInsensitive) }
        guard
            let regex = try? NSRegularExpression(pattern: pattern, options: options),
            let match = regex.firstMatch(
                in: html, range: NSRange(html.startIndex..., in: html)),
            let range = Range(match.range(at: group), in: html)
        else { return nil }
        return String(html[range])
    }

    static func matches(_ pattern: String, in html: String) -> [[String]] {
        guard let regex = try? NSRegularExpression(
            pattern: pattern, options: [.dotMatchesLineSeparators, .caseInsensitive])
        else { return [] }
        return regex.matches(in: html, range: NSRange(html.startIndex..., in: html))
            .map { match in
                (1..<match.numberOfRanges).compactMap { index in
                    Range(match.range(at: index), in: html).map { String(html[$0]) }
                }
            }
    }
}
